spring.application.name=cosmeticsShop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cosmeticsShopDB
spring.datasource.username=cosmet
spring.datasource.password=cosmos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jbdc.time_zone=UTC
spring.jpa.show-sql=true