spring.application.name=cosmeticsShop
spring.config.import=optional:file:auth0.properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cosmeticsShopDB
spring.datasource.username=cosmet
spring.datasource.password=cosmos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jbdc.time_zone=UTC
spring.jpa.show-sql=true
# Spring Security Standard OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_DOMAIN}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE}